version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: warehouse_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse123

    ports:
      - "5432:5432"

    volumes:
      - ./database/data:/var/lib/postgresql/data

    networks:
      - warehouse-network

  backend:

    build: ./backend

    container_name: warehouse_backend

    restart: unless-stopped

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "3000:3000"

    networks:
      - warehouse-network

  frontend:

    build: ./frontend

    container_name: warehouse_frontend

    depends_on:
      - backend

    restart: unless-stopped

    ports:
      - "5173:5173"

    networks:
      - warehouse-network

  nginx:

    build: ./nginx

    restart: unless-stopped

    container_name: warehouse_nginx

    depends_on:
      - frontend

    ports:
      - "80:80"

    networks:
      - warehouse-network

networks:

  warehouse-network: